### ISSUE TITLE
Abbreviated notation for key entities in spring context xml

### ISSUE THREAD

**Issue by Evlikat** [xdcrafts/flower#31]
`<extention id="someExtension">`
instead of
`<bean id="someExtension" class="com.github.xdcrafts.flower.spring.impl.DefaultExtensionFactory">`

`<feature id="someFeature">`
instead of
`<bean id="someFeature" class="com.github.xdcrafts.flower.spring.impl.DefaultFeatureFactory">`

etc.

**Comment by xdcrafts** [comment]
https://github.com/xdcrafts/flower/pull/32

**Comment by xdcrafts** [comment]
- Header example

        <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:f="http://xdcrafts.github.com/schema/flower"
           xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
            http://xdcrafts.github.com/schema/flower
            http://xdcrafts.github.com/schema/flower.xsd">

- Keyword selector example

        <f:keyword-selector id="selector" keyword="request.type" required="true"/>

- Sync flow example

        <f:sync-flow id="mainFlow">
            <f:method>authenticator::authenticate</f:method>
            <f:action>selector</f:action>
            <f:method>receiver::receive</f:method>
        </f:sync-flow>

- Extension example

        <f:extension id="email.Extension" action="email.Flow">
            <f:keyword-value>email</f:keyword-value>
        </f:extension>

- Feature example

        <f:feature id="email.Feature">
            <f:binding extension="email.Extension" selector="selector"/>
        </f:feature>
